#ifndef _MOTIONDETECTORCOREPLUGIN_H
#define _MOTIONDETECTORCOREPLUGIN_H

#ifdef MOTION_DETECTOR_CORE_EXPORTS
#	define MOTION_DETECTOR_CORE_API WXEXPORT
#else
#	define MOTION_DETECTOR_CORE_API WXIMPORT
#endif

#endif // _MOTIONDETECTORCOREPLUGIN_H
